version: '3.8'
services:
  backend:
    build: ./backend
    container_name: abotme-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
  openwebui:
    image: open-webui/open-webui:latest
    container_name: abotme-openwebui
    ports:
      - "3000:8080"
    environment:
      - OWEBUI_BACKEND_URL=http://backend:8000
    depends_on:
      - backend 