"""init

Revision ID: 08d11c2b843d
Revises: 5c650029887b
Create Date: 2025-07-17 17:01:25.145419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d11c2b843d'
down_revision: Union[str, Sequence[str], None] = '5c650029887b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('resume_chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('x0', sa.Float(), nullable=True),
    sa.Column('x1', sa.Float(), nullable=True),
    sa.Column('top', sa.Float(), nullable=True),
    sa.Column('bottom', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('answers',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('resume_chunks')
    op.drop_table('questions')
    op.drop_table('resumes')
    # ### end Alembic commands ###
