"""question에서 answer refer할 수 있도록 수정

Revision ID: 18354199f3b9
Revises: e6b3b143c020
Create Date: 2025-07-18 16:49:19.360832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18354199f3b9"
down_revision: Union[str, Sequence[str], None] = "e6b3b143c020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
