"""add tag table and enum

Revision ID: f59ad5a0ce7b
Revises: 08d11c2b843d
Create Date: 2025-07-18 16:06:38.239877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f59ad5a0ce7b"
down_revision: Union[str, Sequence[str], None] = "08d11c2b843d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=True),
        sa.Column(
            "tag_name",
            sa.Enum(
                "personal",
                "education",
                "experience",
                "project",
                "tech_stack",
                "achievement",
                "certificate",
                "award",
                "timeline",
                "summary",
                name="tag_category",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.question_id"],
        ),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tags")
    # ### end Alembic commands ###
