name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" > .env

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Generate requirements.txt from pyproject.toml
        run: uv pip freeze > requirements.txt

      - name: Install dependencies
        run: uv pip install --system -r requirements.txt

      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 .

      - name: Run tests (pytest)
        run: |
          
          uv run pytest 