name: Backend CD

on:
  push:
    branches: 
      - main
      - cd/backend-deploy
    paths:
      - 'backend/**'
      - '.github/workflows/backend-cd.yml'


jobs:
  backend-cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}\nGOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > .env

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Generate requirements.txt from pyproject.toml
        run: uv pip freeze > requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/abotme
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 

  deploy-railway:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to Railway
        env:
          SVC_ID: ${{ secrets.SVC_ID }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: cd backend/ && railway up --service=${{ secrets.SVC_ID }}